### PR TITLE
Added constants for macOS 14 support

### PR DESCRIPTION
**Pull request by Lorys89**

### CODE REVIEW

**Comment by vit9696** [comment]
No big reason for that, IO80211FamilyLegacy.kext is removed, killing patched Wi-Fi stack.

**Comment by gujiangjiang** [comment]
@vit9696 @PMheart 
Now can using OCLP to fix broadcom wifi card and the [AirportBrcmFixup] still needed for broadcom which drived by OCLP.
Hope to update the kext to support macOS Sonoma it is important for broadcom wifi card even using with OCLP.

Thanks.

**Comment by Andrey1970AppleLife** [comment]
> @vit9696 @PMheart Now can using OCLP to fix broadcom wifi card and the [AirportBrcmFixup] still needed for broadcom which drived by OCLP. Hope to update the kext to support macOS Sonoma it is important for broadcom wifi card even using with OCLP.
> 
> Thanks.

Did you check AirportBrcmFixup for Sonoma with OCLP?

**Comment by gujiangjiang** [comment]
@Andrey1970AppleLife 
Yes.
I'm now using AirportBrcmFixup in Sonoma with OCLP to make DW1830 works.
If dont use [-brcmfxbeta] then it show [Third party wifi]
when use [-brcmfxbeta[ then it show [Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1772.1)]
image


image


So this kext is still necessary for Broadcom wifi chips when using OCLP in Sonoma.

Hope to make it works default in sonoma.

Thanks.

**Comment by Andrey1970AppleLife** [comment]
Done

**Pull request closed without merging**
